name : My First Workflow

on: [push]

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4

# Running multiple steps in a job        

        - name: Welcome Message
          run: |
            echo "Hello, World from Github Actions!"
            ls -ltra
            cat README.md

# Running Third Party Library

        - name: Generate ASCII Artwork
          run: cowsay -f dragon "Hello, World from Github Actions!" >> output.txt


        # - name: list files
        #   run: ls

        # - name: Read Files
        #   run: cat README.md