name: Run Shell Script

on: 
    #[push]
    # Lets Schedule the Workflow to run every minute
    schedule:
      - cron: "*/1 * * * *"

jobs:
  ascii_job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Run Shell Script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh

#Multiple Jobs Example

  ascii_job2:
    needs: ascii_job1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Run Shell Script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh

  ascii_job3:
    needs: ascii_job2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo Files
        run: ls -ltra

      - name: Run Shell Script
        run: |
          chmod +x ./ascii-script.sh
          ./ascii-script.sh
